### ISSUE TITLE
"Unexpected reserved word" error when building

### ISSUE THREAD

**Issue by jkarsrud** [jkarsrud/ember-cli-defeatureify#1]
As of now, [Esprima](http://esprima.org/) doesn't support ES6 good enough to work directly on the app tree. This makes `ember build` fail with an "Unexpected reserved word"-error, and thus doesn't really defeature your code. 

Related issues: 
- https://code.google.com/p/esprima/issues/detail?id=189
- https://code.google.com/p/esprima/issues/detail?id=499

**Comment by rwjblue** [comment]
defeatureify must be run after the ES6 transpilation step

**Comment by jkarsrud** [comment]
@rwjblue Thanks! Is there anyway to access the transpiled modules from an addon?

**Comment by jkarsrud** [comment]
So, using the postprocessTree hook with the 'all'-tree from an addon will make it work, but it takes around 10 seconds in the app I've tested it in. Will look more into how we do it more like emberjs-build, where the list of features are seeded into the page for `development` builds, and only defeatureify on `production` builds.

**Comment by jkarsrud** [comment]
Running this on a production build of an Ember-CLI app seems to make defeatureify freak out — probably because the source has already been minified. This results in a `Cannot read property 'length' of undefined` error from defeatureify — not esprima this time.

**Comment by rwjblue** [comment]
Should be fixable now https://github.com/ember-cli/ember-cli/pull/3117.

**Comment by rwjblue** [comment]
I believe this can be closed.
