### ISSUE TITLE
DEPRECATION: The `app-prefix` hook used in ember-cli-defeatureify is deprecated. The addon should generate a module and have consumers `require` it.

### ISSUE THREAD

**Issue by notmessenger** [jkarsrud/ember-cli-defeatureify#17]
Believe https://github.com/jkarsrud/ember-cli-defeatureify/issues/15 may resolve this though

**Comment by nathanhammond** [comment]
Confirmed, but waiting on ember-cli#5233 to land in order to proceed. Closing this.

**Comment by adamreisnz** [comment]
This is still an issue today with v1.1.1 and `ember-cli` version 2.6.2. Any update on fixing these deprecation warnings?
